# For more information: https://laravel.com/docs/sail
version: '3'
services:
    php:
        build:
            context: ./docker/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: 1000
            WWWGROUP: 1000
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - traefik-proxy
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-proxy
            #
            - traefik.http.routers.school.entrypoints=http,https
            - traefik.http.routers.school.rule=Host(`school.${SERVER_DOMAIN}`)
            - traefik.http.routers.school.tls=true
            - traefik.http.routers.school.tls.certresolver=letsencrypt
            #
            - traefik.http.routers.school.middlewares=dev-headers
            #
            - traefik.http.routers.school.service=school
            #
            - traefik.http.services.school.loadbalancer.server.port=80
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './storage/docker/mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
        labels:
            - traefik.enable=false
    redis:
        image: 'redis:alpine'
        volumes:
            - './storage/docker/redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
        labels:
            - traefik.enable=false
networks:
    traefik-proxy:
        external: true
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
